/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Gpu {
  static create(): Gpu
  requestAdapter(powerPreference?: string | undefined | null): GPUAdapter
  getPreferredCanvasFormat(): string
}
export type GPU = Gpu

export declare class GpuAdapter {
  requestDevice(): GPUDevice
  get limits(): DeviceLimits
  get info(): AdapterInfo
  get isFallbackAdapter(): boolean
}
export type GPUAdapter = GpuAdapter

export declare class GpuBindGroup {

}
export type GPUBindGroup = GpuBindGroup

export declare class GpuBindGroupLayout {

}
export type GPUBindGroupLayout = GpuBindGroupLayout

export declare class GpuBuffer {
  get size(): number
  get usage(): number
  mapAsync(mode: number, offset?: number | undefined | null, size?: number | undefined | null): void
  getMappedRange(offset?: number | undefined | null, size?: number | undefined | null): ArrayBuffer
  unmap(): void
  destroy(): void
}
export type GPUBuffer = GpuBuffer

export declare class GpuCanvas {
  constructor(width: number, height: number)
  get id(): number
  get width(): number
  set width(width: number)
  get height(): number
  set height(height: number)
  readPixels(): Buffer
  destroy(): void
  getContext(contextId: string): GPUCanvasContext
}
export type GPUCanvas = GpuCanvas

export declare class GpuCanvasContext {
  configure(configuration: GPUCanvasConfiguration, device: GpuDevice): void
  getCurrentTexture(): GpuTexture
  unconfigure(): void
}
export type GPUCanvasContext = GpuCanvasContext

export declare class GpuCommandBuffer {

}
export type GPUCommandBuffer = GpuCommandBuffer

export declare class GpuCommandEncoder {
  beginRenderPass(descriptor: RenderPassDescriptor, colorViews: Array<GpuTextureView>, colorResolveViews?: Array<GpuTextureView | undefined | null> | undefined | null, depthStencilView?: GpuTextureView | undefined | null): GPURenderPassEncoder
  beginComputePass(descriptor?: ComputePassDescriptor | undefined | null): GPUComputePassEncoder
  copyBufferToBuffer(source: GpuBuffer, sourceOffset: number, destination: GpuBuffer, destinationOffset: number, size: number): void
  finish(): GPUCommandBuffer
}
export type GPUCommandEncoder = GpuCommandEncoder

export declare class GpuComputePassEncoder {
  setPipeline(pipeline: GpuComputePipeline): void
  setBindGroup(index: number, bindGroup: GpuBindGroup, dynamicOffsets?: Array<number> | undefined | null): void
  dispatchWorkgroups(x: number, y?: number | undefined | null, z?: number | undefined | null): void
  end(): void
}
export type GPUComputePassEncoder = GpuComputePassEncoder

export declare class GpuComputePipeline {
  getBindGroupLayout(index: number): GpuBindGroupLayout
}
export type GPUComputePipeline = GpuComputePipeline

export declare class GpuDevice {
  get queue(): GPUQueue
  get label(): string | null
  get limits(): DeviceLimits
  createBuffer(descriptor: BufferDescriptor): GPUBuffer
  createTexture(descriptor: TextureDescriptor): GPUTexture
  createSampler(descriptor?: SamplerDescriptor | undefined | null): GPUSampler
  createShaderModule(descriptor: ShaderModuleDescriptor): GPUShaderModule
  createBindGroupLayout(descriptor: BindGroupLayoutDescriptor): GPUBindGroupLayout
  createPipelineLayout(descriptor: PipelineLayoutDescriptor, bindGroupLayouts: Array<GPUBindGroupLayout>): GPUPipelineLayout
  createBindGroup(descriptor: BindGroupDescriptor, layout: GPUBindGroupLayout, entries: Array<BindGroupEntry>, buffers?: Array<GPUBuffer> | undefined | null, textures?: Array<GPUTextureView> | undefined | null, samplers?: Array<GPUSampler> | undefined | null): GPUBindGroup
  createRenderPipeline(descriptor: RenderPipelineDescriptor, layout: GPUPipelineLayout | undefined | null, vertexModule: GPUShaderModule, fragmentModule?: GPUShaderModule | undefined | null): GPURenderPipeline
  createComputePipeline(descriptor: ComputePipelineDescriptor, layout: GPUPipelineLayout | undefined | null, module: GPUShaderModule): GPUComputePipeline
  createCommandEncoder(descriptor?: CommandEncoderDescriptor | undefined | null): GPUCommandEncoder
  destroy(): void
}
export type GPUDevice = GpuDevice

/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  constructor(eventCallback?: (((err: Error | null, arg: EventPayload) => any)) | undefined | null)
  /** Initialize GPUI using the native event-loop architecture for this OS. */
  init(options?: WindowOptions | undefined | null): void
  /**
   * Apply a batch of mutations in a single FFI call.
   *
   * Accepts a JSON array of mutation tuples. Each tuple is an array where
   * the first element is the operation name (string) and remaining elements
   * are the arguments:
   *
   *   ["createElement",    id, "type"]
   *   ["destroyElement",   id]
   *   ["appendChild",      parentId, childId]
   *   ["insertBefore",     parentId, childId, beforeId]
   *   ["setStyle",         id, { ...style }]
   *   ["setText",          id, "content"]
   *   ["setEventListener", id, "eventType", true|false]
   *   ["setRoot",          id]
   *   ["setCustomProp",    id, "key", value]
   *
   * Returns accumulated destroyed IDs from all destroyElement ops.
   * Acquires the tree mutex ONCE for the entire batch.
   */
  applyBatch(json: string): Array<number>
  /** Pump the native event loop. Returns false after the last window closes. */
  tick(): boolean
  isInitialized(): boolean
  /**
   * Whether JavaScript must call tick() until it returns false.
   *
   * macOS: tick() pumps AppKit. Windows/Linux: tick() only reports whether
   * the UI thread is still inside `Platform::run`. Both return false after
   * the last window closes so the JS frame loop can exit the process.
   */
  requiresTick(): boolean
  /**
   * The paintable size of the window in logical pixels, excluding any
   * platform title bar. This used to answer a hardcoded 800x600, so anything
   * that turned a mouse position into layout coordinates pointed at the
   * wrong place on every window that was not exactly that size.
   */
  getWindowSize(): WindowSize
  getWindowInsets(): WindowInsets
  /** `"hidden"` | `"minimal"` | `"full"`. Paints into the scene after layout. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Bring the window forward and give it focus. This is how a window opened
   * with `show: false` or `focus: false` is revealed later.
   */
  activateWindow(): void
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  /** Move focus to the next GPUI tab stop. */
  focusNext(): void
  /** Move focus to the previous GPUI tab stop. */
  focusPrevious(): void
  /** Enable the window key events requested by the React renderer. */
  setWindowKeyEvents(keyDown: boolean, keyUp: boolean, eventId: number): void
  blur(): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection and request a repaint. */
  clearSelection(): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   *
   * For a `<virtual-list>` the scroll is queued and applied on the next
   * render, after that frame's child splice, so indices computed against a
   * just-committed child list are never shifted twice. `offsetInItem` is in
   * pixels and may be negative, which anchors the viewport top above the
   * item and resolves against measured heights at layout time.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * The logical scroll anchor of a `<virtual-list>`:
   * `[itemIndex, offsetInItemPx, viewportHeightPx]`, or null for anything
   * else. `itemIndex == item count` is gpui's at-end sentinel.
   *
   * Unlike `getScrollOffset` this is exact even while row heights are still
   * estimates, because it is the anchor gpui itself scrolls by.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  getAutomationTree(): string
  getElementBounds(id: number): Array<number> | null
  getAllText(): Array<string>
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /** Simulate space-separated keystrokes through the focused element's input pipeline. */
  simulateKeystrokes(keystrokes: string): void
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  simulateKeyUp(keystroke: string): void
  /** `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt". */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Dispatch a wheel event through the same GPUI hit test the trackpad uses.
   * Deltas are pixels: negative `delta_y` scrolls down, negative `delta_x`
   * pans right, matching `TestGpuixRenderer::simulate_scroll_wheel`.
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  captureScreenshot(path: string): void
}

export declare class GpuPipelineLayout {

}
export type GPUPipelineLayout = GpuPipelineLayout

export declare class GpuQueue {
  submit(commandBuffers: Array<GPUCommandBuffer>): void
  onSubmittedWorkDone(): void
  writeBuffer(buffer: GPUBuffer, offset: number, data: Buffer, dataOffset?: number | undefined | null, size?: number | undefined | null): void
  get label(): string | null
}
export type GPUQueue = GpuQueue

export declare class GpuRenderPassEncoder {
  setPipeline(pipeline: GpuRenderPipeline): void
  setBindGroup(index: number, bindGroup: GpuBindGroup, dynamicOffsets?: Array<number> | undefined | null): void
  setVertexBuffer(slot: number, buffer: GpuBuffer, offset?: number | undefined | null, size?: number | undefined | null): void
  setIndexBuffer(buffer: GpuBuffer, indexFormat: string, offset?: number | undefined | null, size?: number | undefined | null): void
  draw(vertexCount: number, instanceCount?: number | undefined | null, firstVertex?: number | undefined | null, firstInstance?: number | undefined | null): void
  drawIndexed(indexCount: number, instanceCount?: number | undefined | null, firstIndex?: number | undefined | null, baseVertex?: number | undefined | null, firstInstance?: number | undefined | null): void
  setViewport(x: number, y: number, width: number, height: number, minDepth?: number | undefined | null, maxDepth?: number | undefined | null): void
  setScissorRect(x: number, y: number, width: number, height: number): void
  end(): void
}
export type GPURenderPassEncoder = GpuRenderPassEncoder

export declare class GpuRenderPipeline {
  getBindGroupLayout(index: number): GpuBindGroupLayout
}
export type GPURenderPipeline = GpuRenderPipeline

export declare class GpuSampler {

}
export type GPUSampler = GpuSampler

export declare class GpuShaderModule {

}
export type GPUShaderModule = GpuShaderModule

export declare class GpuTexture {
  createView(descriptor?: TextureViewDescriptor | undefined | null): GPUTextureView
  get width(): number
  get height(): number
  destroy(): void
}
export type GPUTexture = GpuTexture

export declare class GpuTextureView {

}
export type GPUTextureView = GpuTextureView

/**
 * GPU-backed GPUI test renderer. Uses VisualTestAppContext with the native
 * Metal or DirectX renderer and TestDispatcher for deterministic scheduling.
 * Same GpuixView and rendering pipeline as production.
 *
 * Usage from JS:
 *   const r = new TestGpuixRenderer()
 *   r.applyBatch('[["createElement",1,"div"],["setRoot",1]]')
 *   r.flush()                  // triggers GpuixView::render() on the GPU
 *   r.simulateClick(50, 50)    // dispatches through GPUI hit testing
 *   const events = r.drainEvents()
 *   r.captureScreenshot("/tmp/test.png")  // saves rendered UI as PNG
 */
export declare class TestGpuixRenderer {
  constructor(width?: number | undefined | null, height?: number | undefined | null)
  /**
   * How many elements the retained tree holds, reachable from the root or
   * not. `getTreeJson` walks from the root, so it cannot see a node that was
   * detached and never destroyed. This is the only way a test can prove a
   * removal actually freed it.
   */
  getRetainedElementCount(): number
  /**
   * Apply a batch of mutations in a single FFI call.
   * Same format as GpuixRenderer::apply_batch (string op names).
   * Returns accumulated destroyed IDs from all destroyElement ops.
   */
  applyBatch(json: string): Array<number>
  /**
   * Notify the view entity and run GPUI until parked.
   * This triggers GpuixView::render() → build_element() → GPUI layout.
   * Must be called after mutations and before simulating events (GPUI's
   * hit testing requires elements to be laid out).
   */
  flush(): void
  /**
   * Simulate a click at the given window coordinates.
   * Dispatches MouseDown + MouseUp through GPUI's input pipeline,
   * which triggers the same event handlers as production.
   * IMPORTANT: Call flush() before this — hit testing requires laid-out elements.
   * `modifiers` uses the `press()` syntax: "cmd", "cmd-shift", "alt".
   */
  simulateClick(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate key strokes through GPUI's input pipeline.
   * Format: space-separated keys, e.g. "a", "enter", "cmd-shift-p".
   * The focused element receives keyDown/keyUp events.
   */
  simulateKeystrokes(keystrokes: string): void
  /**
   * Simulate a single key down event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Unlike simulate_keystrokes, this dispatches ONLY a KeyDownEvent —
   * no automatic KeyUpEvent follows. Use with simulate_key_up for
   * fine-grained key event testing.
   */
  simulateKeyDown(keystroke: string, isHeld?: boolean | undefined | null): void
  /**
   * Simulate a single key up event through GPUI's input pipeline.
   * Format: modifier-key string, e.g. "a", "enter", "cmd-s".
   * Pairs with simulate_key_down for fine-grained key event testing.
   */
  simulateKeyUp(keystroke: string): void
  /**
   * Simulate a mouse move to the given coordinates.
   * pressed_button: optional mouse button held during move (0=left, 1=middle, 2=right).
   * Used to simulate drag events.
   */
  simulateMouseMove(x: number, y: number, pressedButton?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Focus an element by its numeric ID.
   * The element must have a FocusHandle (created by sync_focus_handles when
   * the element has keyDown, keyUp, focus, or blur listeners).
   * Call flush() before this so the element tree and focus handles exist.
   */
  focusElement(id: number): void
  focusNext(): void
  focusPrevious(): void
  setWindowKeyEvents(keyDown: boolean, keyUp: boolean, eventId: number): void
  /**
   * Simulate a mouse down event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseDown(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate a mouse up event at the given window coordinates.
   * Button: 0=left, 1=middle, 2=right. Defaults to left (0).
   */
  simulateMouseUp(x: number, y: number, button?: number | undefined | null, modifiers?: string | undefined | null): void
  /**
   * Simulate a scroll wheel event at the given position.
   * delta_x and delta_y are in pixels (negative = scroll up/left).
   */
  simulateScrollWheel(x: number, y: number, deltaX: number, deltaY: number, modifiers?: string | undefined | null): void
  /** The current text selection joined in document order, or null. */
  getSelectedText(): string | null
  /** Drop the current selection. */
  clearSelection(): void
  /**
   * Syntax-cache counters as `[hits, misses, documents]`.
   *
   * GPUIX rebuilds its whole element tree every frame, so a `<code>` block
   * that misses the cache reparses at frame rate. A test can watch the hit
   * count to catch that regression before a profiler does.
   */
  getSyntaxCacheStats(): Array<number>
  /**
   * Every string painted in the last frame, in paint order.
   *
   * `getAllText()` only sees `<text>` nodes in the retained tree. Native
   * elements such as `<code>` and `<diff>` draw their text inside gpui, so
   * this is the only way to assert on what they actually rendered.
   */
  getPaintedText(): Array<string>
  /**
   * Every highlight wash painted in the last frame, in paint order.
   *
   * A quad is invisible to `getPaintedText()`, so this is the only way to
   * assert on `highlight` without a screenshot. Each entry carries its rects,
   * so a soft-wrapped match is provably two boxes.
   */
  getPaintedHighlights(): Array<HighlightMatch>
  /**
   * Drag-select from one point to another: mouse down, move, up.
   *
   * A single helper rather than three calls because the listeners that drive
   * selection are registered during **paint**, so a flush must sit between
   * the down and the move. Getting that order wrong silently selects nothing,
   * which is a miserable thing to debug from JS.
   */
  dragSelect(x1: number, y1: number, x2: number, y2: number): void
  /**
   * Set the scroll offset of a scrollable element.
   * x and y are negative pixel values (scroll down = more negative y).
   * Call flush() after to apply the offset and re-render.
   */
  scrollTo(elementId: number, x: number, y: number): void
  /**
   * Scroll a child into view by its index in the children list.
   * Call flush() after to apply and re-render. For a `<virtual-list>` the
   * scroll is queued and applied on that flush, after the child splice.
   * `offset_in_item` is in pixels and may be negative, which anchors the
   * viewport top above the item.
   */
  scrollToItem(elementId: number, index: number, offsetInItem?: number | undefined | null): void
  /**
   * The logical scroll anchor of a `<virtual-list>`:
   * `[itemIndex, offsetInItemPx, viewportHeightPx]`, or null for anything
   * else. `itemIndex == item count` is gpui's at-end sentinel.
   */
  getListScrollTop(elementId: number): Array<number> | null
  /** `"hidden"` | `"minimal"` | `"full"`. */
  setDebugFrameOverlay(mode: string): string
  /** Hidden → minimal → full → hidden. */
  cycleDebugFrameOverlay(): string
  getDebugFrameOverlay(): string
  /** Clears the last 1000 draw samples. Frame count stays. */
  resetDebugFrameOverlayStats(): void
  /** Same numbers as the on-screen overlay: current, p90, p99, max, frames. */
  getDebugFrameOverlayStats(): DebugFrameOverlayStats
  /**
   * Get the current scroll offset of a scrollable element.
   * Returns [x, y] or null if the element has no scroll handle.
   */
  getScrollOffset(elementId: number): Array<number> | null
  /**
   * Capture a screenshot of the current rendered state and save as PNG.
   * Supported on macOS through Metal and Windows through DirectX.
   */
  captureScreenshot(path: string): void
  /**
   * Return and clear all collected events since the last drain.
   * Events are collected synchronously — no event loop queuing.
   */
  drainEvents(): Array<EventPayload>
  /** Get all text content in the tree (depth-first order). */
  getAllText(): Array<string>
  /** Find element IDs matching the given type (e.g. "div", "text"). */
  findByType(elementType: string): Array<number>
  /** Check if an element has a specific event listener. */
  hasEventListener(id: number, eventType: string): boolean
  /** Get the text content of an element. */
  getText(id: number): string | null
  /** Get the full tree as JSON for snapshot testing. */
  getTreeJson(): string
  /** Tree JSON with last-paint bounds. Used by the automation locators. */
  getAutomationTree(): string
  /** Last painted bounds for an element, or null if it was not painted. */
  getElementBounds(id: number): Array<number> | null
  clockPause(): number
  clockSet(nowMs: number): number
  clockFastForward(deltaMs: number): number
  clockResume(): number
  /** Advance GPUI's deterministic test executor and run due timers. */
  advanceTime(milliseconds: number): void
  /** Get the root element ID, or null if no root is set. */
  getRootId(): number | null
  /**
   * The offscreen window size, so `useWindowSize()` reports the same numbers
   * under test as in a real window instead of falling back to a default.
   */
  getWindowSize(): WindowSize
}

export interface AdapterInfo {
  vendor: string
  architecture: string
  device: string
  description: string
}

export interface BindGroupDescriptor {
  label?: string
}

export interface BindGroupEntry {
  binding: number
  resourceType: string
  offset?: number
  size?: number
}

export interface BindGroupLayoutDescriptor {
  label?: string
  entries: Array<BindGroupLayoutEntry>
}

export interface BindGroupLayoutEntry {
  binding: number
  visibility: number
  buffer?: BufferBindingLayout
  sampler?: SamplerBindingLayout
  texture?: TextureBindingLayout
  storageTexture?: StorageTextureBindingLayout
}

export interface BlendComponent {
  srcFactor: string
  dstFactor: string
  operation: string
}

export interface BlendState {
  color: BlendComponent
  alpha: BlendComponent
}

export interface BufferBindingLayout {
  type?: string
  hasDynamicOffset?: boolean
  minBindingSize?: number
}

export interface BufferDescriptor {
  label?: string
  size: number
  usage: number
  mappedAtCreation?: boolean
}

export interface BufferUsage {
  mapRead: number
  mapWrite: number
  copySrc: number
  copyDst: number
  index: number
  vertex: number
  uniform: number
  storage: number
  indirect: number
  queryResolve: number
}

export interface ColorTargetState {
  format: string
  blend?: BlendState
  writeMask?: number
}

export interface CommandEncoderDescriptor {
  label?: string
}

export interface ComputePassDescriptor {
  label?: string
}

export interface ComputePipelineDescriptor {
  label?: string
  entryPoint: string
}

/** Recorded draw times from the debug frame overlay. */
export interface DebugFrameOverlayStats {
  currentMs?: number
  p90Ms?: number
  p99Ms?: number
  maxMs?: number
  frames: number
  samples: number
}

export interface DepthStencilState {
  format: string
  depthWriteEnabled?: boolean
  depthCompare?: string
}

export interface DeviceLimits {
  maxTextureDimension1D: number
  maxTextureDimension2D: number
  maxTextureDimension3D: number
  maxBindGroups: number
  maxBufferSize: number
  maxUniformBufferBindingSize: number
  minUniformBufferOffsetAlignment: number
  maxComputeWorkgroupsPerDimension: number
}

export interface EdgeInsets {
  top: number
  right: number
  bottom: number
  left: number
}

export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  /** Numeric element ID (matches the ID assigned in JS via createElement). */
  elementId: number
  /**
   * Event type string — matches the key used in EVENT_PROPS on the JS side.
   * e.g. "click", "mouseDown", "mouseEnter", "keyDown", "scroll", etc.
   */
  eventType: string
  /** Mouse X position in window coordinates (pixels). */
  x?: number
  /** Mouse Y position in window coordinates (pixels). */
  y?: number
  /**
   * Which mouse button: 0=left, 1=middle, 2=right.
   * Populated for: mouseDown, mouseUp, click, mouseDownOutside, contextMenu.
   */
  button?: number
  /**
   * Number of consecutive clicks (1=single, 2=double, 3=triple).
   * Populated for: mouseDown, mouseUp, click.
   */
  clickCount?: number
  /**
   * Whether this is a right-click (convenience for click events).
   * true when button==2 or ClickEvent::is_right_click().
   */
  isRightClick?: boolean
  /**
   * Which mouse button is currently held during a mouseMove.
   * Same encoding as `button`: 0=left, 1=middle, 2=right.
   * Populated for: mouseMove.
   */
  pressedButton?: number
  /**
   * Key name, e.g. "a", "enter", "escape", "down", "left", "f1".
   * Populated for: keyDown, keyUp.
   */
  key?: string
  /**
   * The character produced by the key press (e.g. "ß" for option-s).
   * May differ from `key` when modifiers are active.
   * Populated for: keyDown, keyUp.
   */
  keyChar?: string
  /**
   * Whether this is a key-repeat event (key held down).
   * Populated for: keyDown.
   */
  isHeld?: boolean
  /**
   * Scroll delta on the X axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaX?: number
  /**
   * Scroll delta on the Y axis (pixels or lines, see `precise`).
   * Populated for: scroll.
   */
  deltaY?: number
  /**
   * true = pixel-precise (trackpad), false = line-based (mouse wheel).
   * Populated for: scroll.
   */
  precise?: boolean
  /**
   * Touch phase for scroll: "started", "moved", "ended".
   * Populated for: scroll (trackpad gestures).
   */
  touchPhase?: string
  /**
   * true = mouse entered element, false = mouse left element.
   * Populated for: mouseEnter, mouseLeave.
   */
  hovered?: boolean
  /**
   * Element-defined string payload.
   * Populated for: `<diff>` toggleFile (the file path), showMore (the
   * hidden line count), and lineClick (the line text); `<markdown>`
   * linkClick (the URL).
   */
  value?: string
  /** Line number on the pre-change side. Populated for: `<diff>` lineClick. */
  oldLine?: number
  /** Line number on the post-change side. Populated for: `<diff>` lineClick. */
  newLine?: number
  /** First visible logical index. Populated for: `<virtual-list>` visibleRange. */
  startIndex?: number
  /** Exclusive end of the visible logical range. Populated for: visibleRange. */
  endIndex?: number
  /**
   * Matches found by this element's `highlight` prop. Counted once per match
   * even when it is split across several painted runs, and it counts every
   * retained match, not only the ones currently on screen.
   * Populated for: highlight.
   */
  matchCount?: number
  modifiers?: EventModifiers
}

export interface FragmentState {
  entryPoint: string
  targets: Array<ColorTargetState>
}

export declare function getPreferredCanvasFormat(): string

export declare function gpuBufferUsage(): BufferUsage

export interface GpuCanvasConfiguration {
  format?: string
  usage?: number
  alphaMode?: string
}

export interface GpuColor {
  r: number
  g: number
  b: number
  a: number
}

export declare function gpuShaderStage(): ShaderStage

export declare function gpuTextureUsage(): TextureUsage

/** True only when this binary compiled the real GPU test renderer. */
export declare function hasTestGpuixRenderer(): boolean

/**
 * One highlight wash painted in the last frame, with the boxes it drew.
 *
 * The rects matter: a quad never lands in `getPaintedText()`, and a match that
 * soft-wraps must produce one box per visual row. Without the geometry the only
 * way to assert either is a screenshot.
 */
export interface HighlightMatch {
  /** Numeric id of the element that painted the run. */
  elementId: number
  /** Index of the run within that element. 0 for a plain `<text>`. */
  sub: number
  /** The full string of the run, so `text.slice(start, end)` is the match. */
  text: string
  /** UTF-16 code-unit offsets into `text`, the units JS strings use. */
  start: number
  end: number
  active: boolean
  rects: Array<HighlightRect>
}

export interface HighlightRect {
  x: number
  y: number
  width: number
  height: number
}

export interface MultisampleState {
  count?: number
  mask?: number
  alphaToCoverageEnabled?: boolean
}

export interface PipelineLayoutDescriptor {
  label?: string
}

export interface PrimitiveState {
  topology?: string
  frontFace?: string
  cullMode?: string
}

export interface RenderPassColorAttachment {
  clearValue?: GpuColor
  loadOp: string
  storeOp: string
}

export interface RenderPassDepthStencilAttachment {
  depthClearValue?: number
  depthLoadOp?: string
  depthStoreOp?: string
}

export interface RenderPassDescriptor {
  label?: string
  colorAttachments: Array<RenderPassColorAttachment>
  depthStencilAttachment?: RenderPassDepthStencilAttachment
}

export interface RenderPipelineDescriptor {
  label?: string
  vertex: VertexState
  primitive?: PrimitiveState
  depthStencil?: DepthStencilState
  multisample?: MultisampleState
  fragment?: FragmentState
}

export interface SamplerBindingLayout {
  type?: string
}

export interface SamplerDescriptor {
  label?: string
  addressModeU?: string
  addressModeV?: string
  addressModeW?: string
  magFilter?: string
  minFilter?: string
  mipmapFilter?: string
  lodMinClamp?: number
  lodMaxClamp?: number
  compare?: string
  maxAnisotropy?: number
}

export interface ShaderModuleDescriptor {
  label?: string
  code: string
}

export interface ShaderStage {
  vertex: number
  fragment: number
  compute: number
}

export interface StorageTextureBindingLayout {
  access?: string
  format: string
  viewDimension?: string
}

export interface TextureBindingLayout {
  sampleType?: string
  viewDimension?: string
  multisampled?: boolean
}

export interface TextureDescriptor {
  label?: string
  width: number
  height: number
  depth?: number
  format: string
  usage: number
  dimension?: string
  mipLevelCount?: number
  sampleCount?: number
}

export interface TextureUsage {
  copySrc: number
  copyDst: number
  textureBinding: number
  storageBinding: number
  renderAttachment: number
}

export interface TextureViewDescriptor {
  label?: string
  format?: string
  dimension?: string
  aspect?: string
  baseMipLevel?: number
  mipLevelCount?: number
  baseArrayLayer?: number
  arrayLayerCount?: number
}

export interface VertexAttribute {
  format: string
  offset: number
  shaderLocation: number
}

export interface VertexBufferLayout {
  arrayStride: number
  stepMode?: string
  attributes: Array<VertexAttribute>
}

export interface VertexState {
  entryPoint: string
  buffers?: Array<VertexBufferLayout>
}

export interface WindowInsets {
  safeArea: EdgeInsets
  ime: EdgeInsets
  effective: EdgeInsets
}

export interface WindowOptions {
  title?: string
  /**
   * The name used inside the macOS "Hide" and "Quit" menu items. Defaults to
   * `title`. It does NOT set the title of the application menu itself: macOS
   * takes that from the executable, and only a `.app` bundle changes it.
   */
  appName?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  /** Plain alpha transparency. Prefer `window_background` when you need blur. */
  transparent?: boolean
  /** Hide the native titlebar so the app can draw chrome under the traffic lights. */
  titlebarTransparent?: boolean
  /**
   * `"opaque"` | `"transparent"` | `"blurred"`. `transparent: true` is the
   * same as `"transparent"` when this is unset.
   */
  windowBackground?: string
  trafficLightX?: number
  trafficLightY?: number
  /**
   * Give the window key focus when it opens. `false` opens it behind the
   * active app, like `open -g`. Ignored on Linux.
   */
  focus?: boolean
  /**
   * Show the window when it opens. `false` opens it hidden; call
   * `activateWindow()` to reveal it. Ignored on Linux.
   */
  show?: boolean
}

export interface WindowSize {
  width: number
  height: number
}
