/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Event payload sent back to JS when a user interacts with an element. */
export interface EventPayload {
  elementId: number
  eventType: string
  x?: number
  y?: number
  key?: string
  modifiers?: EventModifiers
}
export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}
export interface WindowSize {
  width: number
  height: number
}
export interface WindowOptions {
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  transparent?: boolean
}
/** The main GPUI renderer exposed to Node.js. */
export declare class GpuixRenderer {
  constructor(eventCallback?: (err: Error | null, arg: EventPayload) => any | undefined | null)
  /** Initialize the GPUI application with a non-blocking NodePlatform. */
  init(options?: WindowOptions | undefined | null): void
  createElement(id: number, elementType: string): void
  /**
   * Destroy an element and all descendants. Returns array of destroyed IDs
   * so JS can clean up event handlers for the entire subtree.
   */
  destroyElement(id: number): Array<number>
  appendChild(parentId: number, childId: number): void
  removeChild(parentId: number, childId: number): void
  insertBefore(parentId: number, childId: number, beforeId: number): void
  setStyle(id: number, styleJson: string): void
  setText(id: number, content: string): void
  setEventListener(id: number, eventType: string, hasHandler: boolean): void
  /** Set the root element (called from appendChildToContainer). */
  setRoot(id: number): void
  /** Signal that a batch of mutations is complete. Triggers re-render. */
  commitMutations(): void
  tick(): void
  isInitialized(): boolean
  getWindowSize(): WindowSize
  setWindowTitle(title: string): void
  focusElement(elementId: number): void
  blur(): void
}
