/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Event payload sent back to JS */
export interface EventPayload {
  elementId: string
  eventType: string
  x?: number
  y?: number
  key?: string
  modifiers?: EventModifiers
}
export interface EventModifiers {
  shift: boolean
  ctrl: boolean
  alt: boolean
  cmd: boolean
}
export interface WindowSize {
  width: number
  height: number
}
export interface WindowOptions {
  title?: string
  width?: number
  height?: number
  minWidth?: number
  minHeight?: number
  resizable?: boolean
  fullscreen?: boolean
  transparent?: boolean
}
/** The main GPUI renderer exposed to Node.js */
export declare class GpuixRenderer {
  constructor(eventCallback?: (err: Error | null, arg: EventPayload) => any | undefined | null)
  render(treeJson: string): void
  run(): void
  stop(): void
  isRunning(): boolean
  getWindowSize(): WindowSize
  setWindowTitle(title: string): void
  focusElement(elementId: string): void
  blur(): void
}
